In [6]:
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("Rochester.csv")
data

,PHS @ Rochester — All Athletes — Averages,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61
0,Games,GP,0,eFG%,TO%,OREB%,DREB%,FTF,VPS,0,...,PPSLOB,BLOB,BLOB%,PPBLOB,0,DEFL,STL,BLK,FOUL,CHG
1,Overall,1,0,52.00%,14.30%,34.50%,75.00%,0.37,0.99,0,...,0.71,11,36.40%,0.64,0,4,10,0,19,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,By Period,GP,0,eFG%,TO%,OREB%,DREB%,FTF,VPS,0,...,PPSLOB,BLOB,BLOB%,PPBLOB,0,DEFL,STL,BLK,FOUL,CHG
4,1st,1,0,32.10%,5.90%,25.00%,66.70%,0.29,0.92,0,...,0,5,40.00%,0.6,0,2,2,0,1,0
5,2nd,1,0,65.00%,28.60%,33.30%,100.00%,0,0.88,0,...,1,1,0.00%,0,0,1,3,0,5,0
6,3rd,1,0,46.70%,13.20%,66.70%,100.00%,0.67,0.95,0,...,0,3,33.30%,0.67,0,1,3,0,6,0
7,4th,1,0,70.80%,12.20%,0.00%,66.70%,0.42,1.21,0,...,2,2,50.00%,1,0,0,2,0,7,0

In [7]:
data.columns = data.iloc[0]
data.rename(columns = {"Games": "Period"}, inplace = True)
data = data.drop([0,2,3])
data.drop(["GP", 0.0], axis = 1, inplace = True)
data

,Period,eFG%,TO%,OREB%,DREB%,FTF,VPS,FGM,FGA,FG%,...,SLOB%,PPSLOB,BLOB,BLOB%,PPBLOB,DEFL,STL,BLK,FOUL,CHG
1,Overall,52.00%,14.30%,34.50%,75.00%,0.37,0.99,25,51,49.00%,...,28.60%,0.71,11,36.40%,0.64,4,10,0,19,0
4,1st,32.10%,5.90%,25.00%,66.70%,0.29,0.92,4,14,28.60%,...,0.00%,0,5,40.00%,0.6,2,2,0,1,0
5,2nd,65.00%,28.60%,33.30%,100.00%,0,0.88,6,10,60.00%,...,33.30%,1,1,0.00%,0,1,3,0,5,0
6,3rd,46.70%,13.20%,66.70%,100.00%,0.67,0.95,7,15,46.70%,...,0.00%,0,3,33.30%,0.67,1,3,0,6,0
7,4th,70.80%,12.20%,0.00%,66.70%,0.42,1.21,8,12,66.70%,...,100.00%,2,2,50.00%,1,0,2,0,7,0

In [8]:
game = data[:1].reset_index(drop = True)
quarters = data[1:].reset_index(drop = True)
game.iloc[0,0] = "Rochester"
game.rename(columns = {"Period": "Opponent"}, inplace = True)
game

,Opponent,eFG%,TO%,OREB%,DREB%,FTF,VPS,FGM,FGA,FG%,...,SLOB%,PPSLOB,BLOB,BLOB%,PPBLOB,DEFL,STL,BLK,FOUL,CHG
0,Rochester,52.00%,14.30%,34.50%,75.00%,0.37,0.99,25,51,49.00%,...,28.60%,0.71,11,36.40%,0.64,4,10,0,19,0

In [9]:
quarters

,Period,eFG%,TO%,OREB%,DREB%,FTF,VPS,FGM,FGA,FG%,...,SLOB%,PPSLOB,BLOB,BLOB%,PPBLOB,DEFL,STL,BLK,FOUL,CHG
0,1st,32.10%,5.90%,25.00%,66.70%,0.29,0.92,4,14,28.60%,...,0.00%,0,5,40.00%,0.6,2,2,0,1,0
1,2nd,65.00%,28.60%,33.30%,100.00%,0,0.88,6,10,60.00%,...,33.30%,1,1,0.00%,0,1,3,0,5,0
2,3rd,46.70%,13.20%,66.70%,100.00%,0.67,0.95,7,15,46.70%,...,0.00%,0,3,33.30%,0.67,1,3,0,6,0
3,4th,70.80%,12.20%,0.00%,66.70%,0.42,1.21,8,12,66.70%,...,100.00%,2,2,50.00%,1,0,2,0,7,0

In [10]:
# game.to_csv("Rochester_game_data.csv", index = False)
# quarters.to_csv("Rochester_quarters_data.csv", index = False)