In [1]:
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("@ Summit.csv")
data

,PHS @ Summit Academy — All Athletes — Averages,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61
0,Games,GP,0,eFG%,TO%,OREB%,DREB%,FTF,VPS,0,...,PPSLOB,BLOB,BLOB%,PPBLOB,0,DEFL,STL,BLK,FOUL,CHG
1,Overall,1,0,53.00%,46.80%,36.40%,57.50%,0.36,0.61,0,...,0.5,6,0.00%,0,0,6,4,1,16,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,By Period,GP,0,eFG%,TO%,OREB%,DREB%,FTF,VPS,0,...,PPSLOB,BLOB,BLOB%,PPBLOB,0,DEFL,STL,BLK,FOUL,CHG
4,1st,1,0,50.00%,52.40%,33.30%,87.50%,0,0.55,0,...,2,2,0.00%,0,0,1,1,0,4,0
5,2nd,1,0,42.90%,52.80%,33.30%,33.30%,0.86,0.49,0,...,0,2,0.00%,0,0,2,2,1,4,0
6,3rd,1,0,66.70%,39.10%,33.30%,63.60%,0.44,0.71,0,...,0,1,0.00%,0,0,2,0,0,6,0
7,4th,1,0,50.00%,38.60%,50.00%,55.60%,0.29,0.75,0,...,0,1,0.00%,0,0,1,1,0,2,0